services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devel
      POSTGRES_DB: classroom
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
